# Generated by Django 4.2.24 on 2025-11-04 00:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vigilante', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='id_paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vigilante.paquete'),
        ),
        migrations.AlterField(
            model_name='registrocorrespondencia',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sorteo',
            name='hora_sorteo',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
