# Generated by Django 4.2.24 on 2025-11-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_novedades_id_paquete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosreserva',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En espera', max_length=15),
        ),
    ]
