# Generated by Django 4.2.24 on 2025-11-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_procesovalidacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivovehiculo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detalleresidente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallesparqueadero',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='entregacorrespondencia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ganadorsorteo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='novedades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pagosreserva',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='parqueadero',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='registrocorrespondencia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sorteo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoarchivo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehiculoresidente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='zonacomun',
            options={'managed': True},
        ),
    ]
