# Generated by Django 4.2.24 on 2025-11-03 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(db_column='id_paquete', primary_key=True, serialize=False)),
                ('apartamento', models.IntegerField()),
                ('torre', models.IntegerField()),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('nombre_residente', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_cedula', models.ImageField(blank=True, null=True, upload_to='cedulas_entrega/')),
                ('cod_usuario_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_entrega', to='usuario.usuario')),
                ('cod_usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_recepcion', to='usuario.usuario')),
            ],
            options={
                'db_table': 'paquete',
                'managed': True,
            },
        ),
    ]
